on:
    push:
      branches:
        - main
  
name: Build My Apps
  
jobs:
    build:
      name: Build and Release new apk
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
  
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter build apk --no-tree-shake-icons

        - name: Get version
          id: get_version
          run: |
            echo ::set-output name=VERSION::$(grep "version:" pubspec.yaml | awk -F "+" '{print $1}' | sed 's/version: //g' | tr -d ' ')
          
        - name: Rename apk
          run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Guzty_MBU_v${{ steps.get_version.outputs.VERSION }}.apk

        - name: Push to Releases
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/flutter-apk/Guzty_MBU_v${{ steps.get_version.outputs.VERSION }}.apk"
            tag: v${{ steps.get_version.outputs.VERSION }}
            token: ${{ secrets.TOKEN }}
